version = 0.1
[default.deploy.parameters]
stack_name = "ocsf-infra-5"
resolve_s3 = true
s3_prefix = "ocsf-infra-5"
region = "ap-southeast-2"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "LogEventSource=\"KinesisDataStream\" ASLCustomLogSourceLocation=\"aws-security-data-lake-ap-southeast-2-uab87sjpgm1cam97ylvaw6ras/ext/windows-sysmon\" RawLogS3BucketName=\"\" KinesisUserARNs=\"arn:aws:iam::837460776723:role/Cloud9Admin\" KinesisStreamEncryptionKeyAdminARNs=\"arn:aws:iam::837460776723:role/aws-reserved/sso.amazonaws.com/ap-southeast-2/AWSReservedSSO_AWSAdministratorAccess_d9181b0bad57f338\""
image_repositories = []
