AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template sets up the temporary log storage bucket for AWS Glue to perform ETL tasks for Amazon Security Lake custom sources.

Resources:
  StagingLogBucket:
    Type: AWS::S3::Bucket

  StagingLogBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StagingLogBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AWSLogDeliveryWrite
            Action:
              - s3:PutObject
            Effect: Allow
            Resource: !Sub 'arn:aws:s3:::${StagingLogBucket}/*'
            Principal:
              Service: delivery.logs.amazonaws.com
            Condition:
              StringEquals:
                "s3:x-amz-acl": "bucket-owner-full-control"
          - Sid: AWSLogDeliveryAclCheck
            Action:
              - s3:GetBucketAcl
            Effect: Allow
            Resource: !Sub 'arn:aws:s3:::${StagingLogBucket}'
            Principal:
              Service: delivery.logs.amazonaws.com

Outputs:
  StagingLogBucketARN:
    Description: Name of the bucket for temporary log storage.
    Value: !GetAtt StagingLogBucket.Arn