AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template creates an IAM role for the AWS Glue configuration for the Security Lake custom source.
Parameters:
  CustomSourceName:
    Type: String
    Description: Name of the custom source.
  ASLCustomLogSourceLocation:
    Type: String
    Description: Amazon Security Lake (ASL) S3 bucket name with custom log location excluding the trailing slash (eg. my_bucket/ext/my_custom_source)

Resources:
  CustomSourceGlueRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['', [ !Ref CustomSourceName, '-glue-role'] ]
      Path: "/service-role/"
      Policies:
        - PolicyName: !Join ['', [ !Ref CustomSourceName, '-glue-policy'] ]
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: S3WriteRead
                Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                Resource: !Sub 'arn:aws:s3:::${ASLCustomLogSourceLocation}/*'
              - Sid: GlueServicePolicy
                Effect: Allow
                Action:
                  - glue:*
                  - s3:GetBucketLocation
                  - s3:ListBucket
                  - s3:ListAllMyBuckets
                  - s3:GetBucketAcl
                  - ec2:DescribeVpcEndpoints
                  - ec2:DescribeRouteTables
                  - ec2:CreateNetworkInterface
                  - ec2:DeleteNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeSubnets
                  - ec2:DescribeVpcAttribute
                  - iam:ListRolePolicies
                  - iam:GetRole
                  - iam:GetRolePolicy
                  - cloudwatch:PutMetricData
                Resource: '*'
              - Sid: GlueS3Create
                Effect: Allow
                Action:
                  - s3:CreateBucket
                Resource: arn:aws:s3:::aws-glue-*
              - Sid: GlueS3ReadWrite
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource:
                  - arn:aws:s3:::aws-glue-*/*
                  - arn:aws:s3:::*/*aws-glue-*/*
              - Sid: GlueCrawlerS3Read
                Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - arn:aws:s3:::crawler-public*
                  - arn:aws:s3:::aws-glue-*
              - Sid: GlueLogging
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*:/aws-glue/*
              - Sid: EC2CreateTags
                Effect: Allow
                Condition:
                  "ForAllValues:StringEquals":
                    "aws:TagKeys": "aws-glue-service-resource"
                Action:
                  - ec2:CreateTags
                  - ec2:DeleteTags
                Resource:
                  - arn:aws:ec2:*:*:network-interface/*
                  - arn:aws:ec2:*:*:security-group/*
                  - arn:aws:ec2:*:*:instance/*
              
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole
Outputs:
  CustomSourceGlueRoleARN:
    Description: ARN of the IAM role created for Glue to use with custom sources.
    Value: !GetAtt CustomSourceGlueRole.Arn