AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template creates a Kinesis Data Firehose delivery stream to deliver custom log data into Amazon Security Lake S3 buckets.
  The template requires the OCSF conversion Lambda function ARN and custom source details like Security Lake S3 bucket details and log delivery prefix.
  The template also sets up an Amazon CloudWatch Alarm to alert when Kinesis Data Firehose stream's log delivery rate falls below 95%.
Parameters:
  CustomSourceName:
    Type: String
    Description: Name of the custom source created in Security Lake.
  LogCollectionS3BucketARN:
    Type: String
    Description: Security Lake bucket in the region where you are deploying the Kinesis Data Firehose.
  OCSFConversionLambdaFunctionARN:
    Type: String
    Description: ARN of the AWS Lambda function created for OCSF conversion.
  S3LogDeliveryPrefix:
    Type: String
    Description: Log delivery prefix in the Security Lake S3 buckets
  BufferingSize:
    Type: Number
    Default: 128
  BufferingInterval:
    Type: Number
    Default: 300

Resources:

  WindowsSysmonGlueRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "WindowsSysmonGlueRole"
      Path: "/service-role/"
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole"
      Policies:
      - PolicyName: WindowsSysmonGluePolicy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
              - Sid: S3WriteRead
                Effect: Allow
                Action:
                  - "s3:GetObject",
                  - "s3:PutObject"
                Resource: "arn:aws:s3:::aws-security-data-lake-*/*"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole

  KDFCustomSourceIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
        Version: 2012-10-17
      Policies:
        - PolicyName: WriteLogData
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - 's3:AbortMultipartUpload'
                  - 's3:GetBucketLocation'
                  - 's3:GetObject'
                  - 's3:ListBucket'
                  - 's3:ListBucketMultipartUploads'
                  - 's3:PutObject'
                Effect: Allow
                Resource:
                  - !Ref LogCollectionS3BucketARN
                  - !Join [ '', [ !Ref LogCollectionS3BucketARN, '/', '*' ] ]
        - PolicyName: InvokeConversionLambda
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'lambda:InvokeFunction'
                  - 'lambda:GetFunctionConfiguration'
                Resource: 
                  - !Join ['', [ !Ref OCSFConversionLambdaFunctionARN, '*'] ]

  KDFCustomSourceDeliveryStream:
    DependsOn: KDFCustomSourceIAMRole
    Type: 'AWS::KinesisFirehose::DeliveryStream'
    Properties:
      DeliveryStreamName: !Join ['', ['KDFFor', !Ref CustomSourceName ] ]
      DeliveryStreamType: DirectPut
      DeliveryStreamEncryptionConfigurationInput:
        KeyType: AWS_OWNED_CMK
      ExtendedS3DestinationConfiguration:
        BucketARN: !Ref LogCollectionS3BucketARN
        BufferingHints:
          IntervalInSeconds: !Ref BufferingInterval
          SizeInMBs: !Ref BufferingSize
        ErrorOutputPrefix: !Join [ '', [ !Ref S3LogDeliveryPrefix, "error/!{firehose:error-output-type}/dt=!{timestamp:yyyy'-'MM'-'dd}/h=!{timestamp:HH}/"] ]
        Prefix: !Ref S3LogDeliveryPrefix
        RoleARN: !GetAtt 
          - KDFCustomSourceIAMRole
          - Arn
        ProcessingConfiguration:
          Enabled: true
          Processors:
          - Type: Lambda
            Parameters:
              - ParameterName: LambdaArn
                ParameterValue: !Ref OCSFConversionLambdaFunctionARN

  MonitoringPutRecordAlarm:
    DependsOn: KDFCustomSourceDeliveryStream
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      ComparisonOperator: LessThanOrEqualToThreshold
      EvaluationPeriods: 2
      Dimensions:
        - Name: StreamName
          Value: !Ref KDFCustomSourceDeliveryStream
      MetricName: PutRecord.Success
      Namespace: AWS/Kinesis
      Period: 60
      Statistic: Average
      Threshold: 0.95
      TreatMissingData: notBreaching

Outputs:
  WindowsSysmonGlueRoleARN:
    Description: Name of the IAM role created for Glue to use with custom sources.
    Value: !GetAtt WindowsSysmonGlueRole.Arn

  CustomSourceKDFStreamName:
    Description: Name of the Amazon Kinesis Data Firehose delivery stream.
    Value: !Ref KDFCustomSourceDeliveryStream

  KinesisMonitoringPutRecordAlarm:
    Description: Name of the Amazon CloudWatch alarm that monitors healthy Kinesis operation.
    Value: !Ref MonitoringPutRecordAlarm

